[package]
name = "scanner"
version = "0.5.0"
edition = "2021"

[dependencies.ptrsx]
path = "../ptrsx"
default-features = false

[dependencies.argh]
version = "0.1.12"
default-features = false

[dependencies.terminal_size]
version = "0.3.0"
default-features = false
