[package]
name = "scanner"
version = "0.7.0"
edition = "2021"

[dependencies.ptrsx]
path = "../ptrsx"
default-features = false

[dependencies.rayon]
version = "1.8.0"
default-features = false

[dependencies.argh]
version = "0.1.12"
default-features = false
