[package]
name = "scanner"
version = "0.4.1"
edition = "2021"

[dependencies.ptrsx]
path = "../ptrsx"
default-features = false
features = ["scanner"]

[dependencies.argh]
version = "0.1.12"
default-features = false

[dependencies.terminal_size]
version = "0.3.0"
default-features = false

[dependencies.rayon]
version = "1.8.0"
default-features = false
