[package]
name = "dumper"
version = "0.7.0"
edition = "2021"

[dependencies.vmmap]
path = "../vmmap"
default-features = false

[dependencies.ptrsx]
path = "../ptrsx"
default-features = false

[dependencies.argh]
version = "0.1.12"
default-features = false
